export const FLASH_MSG_IGNORED_KEY = 'FLASH_MSG_IGNORED_KEY';
export const IS_DEEZER_CONNECTED_KEY = 'IS_DEEZER_CONNECTED_KEY';
export const IS_DEEZER_DISABLED_KEY = 'IS_DEEZER_DISABLED_KEY';

export const SPOTIFY_PLAYER_MSG_IGNORED_KEY = 'SPOTIFY_PLAYER_MSG_IGNORED_KEY';
export const SPOTIFY_AUTH_KEY = 'SPOTIFY_AUTH_KEY';
export const IS_SPOTIFY_DISABLED_KEY = 'IS_SPOTIFY_DISABLED_KEY';