export const DEEZER_SERVICE_CTX_KEY = 'DEEZER_SERVICE_CTX_KEY';
export const SPOTIFY_SERVICE_CTX_KEY = 'SPOTIFY_SERVICE_CTX_KEY';
export const AXIOS_CTX_KEY = 'AXIOS_CTX_KEY';
export const AUDIO_SERVICE_CTX_KEY = 'AUDIO_SERVICE_CTX_KEY';
